import { configureStore } from '@reduxjs/toolkit';
import {
  partnersApi,
  citiesApi,
  regionsApi,
  bookingsApi,
  clientsApi,
  servicePointsApi,
  carBrandsApi,
  carModelsApi,
  dashboardApi,
  authApi,
  usersApi,
  tireTypesApi,
  carTypesApi,
  reviewsApi,
  scheduleApi,
  serviceCategoriesApi,
  servicePointPhotosApi,
  servicePointServicesApi,
} from '../api';

export const store = configureStore({
  reducer: {
    [partnersApi.reducerPath]: partnersApi.reducer,
    [citiesApi.reducerPath]: citiesApi.reducer,
    [regionsApi.reducerPath]: regionsApi.reducer,
    [bookingsApi.reducerPath]: bookingsApi.reducer,
    [clientsApi.reducerPath]: clientsApi.reducer,
    [servicePointsApi.reducerPath]: servicePointsApi.reducer,
    [carBrandsApi.reducerPath]: carBrandsApi.reducer,
    [carModelsApi.reducerPath]: carModelsApi.reducer,
    [dashboardApi.reducerPath]: dashboardApi.reducer,
    [authApi.reducerPath]: authApi.reducer,
    [usersApi.reducerPath]: usersApi.reducer,
    [tireTypesApi.reducerPath]: tireTypesApi.reducer,
    [carTypesApi.reducerPath]: carTypesApi.reducer,
    [reviewsApi.reducerPath]: reviewsApi.reducer,
    [scheduleApi.reducerPath]: scheduleApi.reducer,
    [serviceCategoriesApi.reducerPath]: serviceCategoriesApi.reducer,
    [servicePointPhotosApi.reducerPath]: servicePointPhotosApi.reducer,
    [servicePointServicesApi.reducerPath]: servicePointServicesApi.reducer,
  },
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(
      partnersApi.middleware,
      citiesApi.middleware,
      regionsApi.middleware,
      bookingsApi.middleware,
      clientsApi.middleware,
      servicePointsApi.middleware,
      carBrandsApi.middleware,
      carModelsApi.middleware,
      dashboardApi.middleware,
      authApi.middleware,
      usersApi.middleware,
      tireTypesApi.middleware,
      carTypesApi.middleware,
      reviewsApi.middleware,
      scheduleApi.middleware,
      serviceCategoriesApi.middleware,
      servicePointPhotosApi.middleware,
      servicePointServicesApi.middleware,
    ),
}); 